### ISSUE TITLE
04/08 - Accomplishments and Todos

### ISSUE THREAD

**Issue by mingzhaogu** [mingzhaogu/holler#10]
## Accomplishments
- cleaned up a LOT of code
- factored out icon-links -- may need to rearrange file tree
- started to kind of sort of not really understand Action Cable
- recognize when currentUser === sender, and format messages accordingly
- include and style user's imageUrl

## Todos
- [x] fix async for `fetchConversation` when clicking between conversations
- [x] draft of ActionCable by Monday night?
- [ ] hover on messages for timestamp
- [x] add more seed data
  - [x] test if adding to conversations will add to joins table

## Challenges
- figuring out Action Cable
- not understanding terminology and functions
- not just implementing it in rails, but also incorporating it with react/redux
