### ISSUE TITLE
04/03 - Accomplishments and Todos

### ISSUE THREAD

**Issue by mingzhaogu** [mingzhaogu/holler#3]
## Accomplishments:
- finished backend auth
- pretty much done with frontend auth
  - bootstrapping current user
  - auth/protected routes
- able to have a pretty-looking log in/sign in page! :)

## Todos for User Auth:
- [x] work on rendering a page after logging in/signing up
- [x] NavBar Component:
  - [x] Nav
    - [x] cog to log out (change to dropdown later)
- [x] push to Heroku

## Other Todos:
- [x] PA Review Issue for next MVP
- [x] learn Action Cable
- [x] GIPHY API (after being able to send messages)

## Things to ask PA:
- [x] is it okay to route to an organizational component, then have subcomponents with containers?
  + e.g. NavBar does not need to be a container, but MessageList (within NavBar) may need a container
- [x] is it necessary/reasonable to factor out Logo into a mini-component?

**Comment by mingzhaogu** [comment]
- [ ] might need to edit auth/protected routes? need to render protected route when signed in, without redirect.
