### ISSUE TITLE
04/05 - Accomplishments and Todos

### ISSUE THREAD

**Issue by mingzhaogu** [mingzhaogu/holler#7]
## Accomplishments
- fully finished user auth (with minor fixes still needed)
- set up messages, conversations, conversation_users tables with proper associations
- set up views for messages/conversations
- added ajax request/actions for conversations

## Todos
- [x] fix session form - error not going away
- [x] figure out conversation name (default other user/convo id?)
- [x] add (default) img_url to conversation?
- [x] on select, maintain background color of messagelist convo
- [x] main -> head
