### ISSUE TITLE
04/06 - Accomplishments and Todos

### ISSUE THREAD

**Issue by mingzhaogu** [mingzhaogu/holler#8]
## Accomplishments
- fixed session form error
- message list contains convos of only current user -- may need to revisit
- revamped controllers and views
- rendered different routes for different conversations
- selected conversation stays gray
- start MessageView -- 2 containers, 1 component
- started learning ActionCable

## Todos
- [x] on logout/componentWillUnmount, set state to empty
- [x] continue working on MessageView
- [x] what is reduxform?
- [x] continue learning ActionCable
