### ISSUE TITLE
04/07 - Accomplishments and Todos

### ISSUE THREAD

**Issue by mingzhaogu** [mingzhaogu/holler#9]
## Accomplishments
- message input working!
- submit with 'enter' or click send
- retract/display sidebar on click
- implemented drop down for logout with click and clickaway
- debug sooooo much code
- revamped conversations json
- fixed conversations reducer

## Todos
- [x] continue learning action cable
- [x] clear session after logout?
- [x] ACTIONCABLE, ACTIONCABLE, ACTIONCABLE
- [x] do I need to have messageinput and livechat in the same file?
